apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://localhost:8080
  oidc.config: |
    name: GitHub
    issuer: https://github.com
    clientID: $GITHUB_CLIENT_ID
    clientSecret: $GITHUB_CLIENT_SECRET
    requestedScopes: ["openid", "profile", "email", "read:org"]
